DROP TABLE equipo;

CREATE TABLE `equipo` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nombre` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO equipo VALUES("1","Los Cobras","2016-12-27 10:26:08");
INSERT INTO equipo VALUES("2","Los Chicos","2016-12-27 10:26:20");
INSERT INTO equipo VALUES("3","El equipote","2016-12-30 07:18:36");



DROP TABLE jugador;

CREATE TABLE `jugador` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `seccion` int(11) NOT NULL,
  `pos` int(11) NOT NULL,
  `apellido_paterno` varchar(25) COLLATE utf8_unicode_ci NOT NULL,
  `apellido_materno` varchar(25) COLLATE utf8_unicode_ci NOT NULL,
  `nombres` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `calle` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `numero_int` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `numero_ext` varchar(20) COLLATE utf8_unicode_ci NOT NULL,
  `colonia` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `cp` varchar(10) COLLATE utf8_unicode_ci NOT NULL,
  `localidad` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `municipio` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `estado` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `tlf_particular` varchar(30) COLLATE utf8_unicode_ci NOT NULL,
  `tlf_celular` varchar(30) COLLATE utf8_unicode_ci NOT NULL,
  `correo` varchar(100) COLLATE utf8_unicode_ci NOT NULL,
  `facebook` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
  `twitter` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
  `youtube` varchar(200) COLLATE utf8_unicode_ci NOT NULL,
  `equipo_id` int(11) DEFAULT NULL,
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO jugador VALUES("1","1","2","Irazabal","Gonzalez","Jaime Alfonso","calle","123456","654321","Colonia","1203","Local","Muni","Estado","04143299925","041432656456","jaimeirazabal1@gmail.com","facebook","twitter","youtube","","2016-12-27 11:56:37");
INSERT INTO jugador VALUES("2","2","3","Apellido p","Apellido m","Nombres","Calle 2","1234569","987651","Colonia","CP","localidad","Municipio","Estado","123456789","987654321","jaimeirazabal1@gmail.com","Facebook","twitter","youtube","1","2016-12-27 11:57:50");



DROP TABLE jugadores;

CREATE TABLE `jugadores` (
  `id` int(9) NOT NULL,
  `seccion` int(6) NOT NULL,
  `posicion` int(4) NOT NULL,
  `apellidopaterno` varchar(30) NOT NULL,
  `apellidomaterno` varchar(30) NOT NULL,
  `nombre` varchar(40) NOT NULL,
  `calle` varchar(60) NOT NULL,
  `numeroexterior` varchar(10) NOT NULL,
  `numerointerior` varchar(10) NOT NULL,
  `colonia` varchar(60) NOT NULL,
  `localidad` int(6) NOT NULL,
  `municipio` int(4) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO jugadores VALUES("1","1","19","AGUILAR","CASARES","JUAN ERNESTO","C ABASOLO","16A","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("2","1","99","AGUILAR","DE HARO","HERIBERTO","C ALDAMA","29 A","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("3","1","19","AGUILAR","MORENO","OLGA MARGARITA","C ABASOLO","16 A","","","1","1");
INSERT INTO jugadores VALUES("4","1","2","ACOSTA","LOPEZ","JULIO CESAR","C ABASOLO","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("5","1","38","TIRADO","FLORES","URBICIA","C LIMITE DE VIA","11","","","1","1");
INSERT INTO jugadores VALUES("6","1","45","TORRES","CRUZ","RAQUEL GREGORIA","C LIMITE","27","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("7","1","99","TIRADO","AGUILA","JESUS MIGUEL","C ALDAMA","33","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("8","1","2","TAPIA","ZARCO","RAFAEL","C MERIDA","S/N","","COL RAFAEL","1","1");
INSERT INTO jugadores VALUES("9","1","61","SOTO","FLORES","JULIA","C ABASOLO","SN","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("10","1","60","SOTO","AHUMADA","MARIA DEL CARMEN","C ALDAMA","34","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("11","1","29","ESPAIN","GARAY","RAFAELA","C ABASOLO","11","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("12","1","45","CASILLAS","MURILLO","ALEJANDRO","C LIMITE DE VIA","35","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("13","1","75","CASARES","ESCALANTE","GUADALUPE","C MAZATLANCITO","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("14","1","45","GUERRERO","RAMIREZ","MARIA FELIX","C ALDAMA","36","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("15","1","99","AGUILA","XX","ROSALBA MARGARITA","C ALDAMA","33PTE","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("16","1","61","ALVAREZ","GARAY","VALENTE","C RAYON","SN","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("17","1","20","ALVALLE","HERNANDEZ","EUGENIO","C LA PAZ","7","","BARR EL ESTADIO","1","1");
INSERT INTO jugadores VALUES("18","1","29","ALMANZA","LAGUNA","PAULINO","C JUAN ESCUTIA","7","","","1","1");
INSERT INTO jugadores VALUES("19","1","71","ALVAREZ","ORTEGA","GUADALUPE BEATRIZ","C ALDAMA","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("20","1","3","ALATORRE","ROMERO","SALOME","C ALDAMA","42","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("21","1","71","ALVALLE","SOLIZ","BERNARDO","C FERROCARRIL","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("22","1","71","ALVALLE","SOLIS","HECTOR MARIO","C ALDAMA","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("23","1","71","ALVALLE","SOLIS","REGINA","C ALDAMA","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("24","1","45","ARIAS","DELGADO","MACARIA","C ALDAMA","36","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("25","1","45","ARTEAGA","NAVA","NATIVIDAD","C LIMITE DE VIA","29","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("26","1","99","TIRADO","AGUILA","JOSUE SAMUEL","C ALDAMA PONIENTE","33","","MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("27","1","2","BAHENA","GARCIA","GASPAR","C ALDAMA","41 PTE","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("28","1","60","SANCHEZ","TAPIA","MARIA FELICITAS","C LIMITE","37","","BARR MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("29","1","2","SOTO","MENDOZA","GILBERTO","C ALDAMA","39 PTE","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("30","1","2","SOTO","PARTIDA","GILBERTO","C ALDAMA","39","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("31","1","99","TOLEDO","MEDINA","ARTURO","C ALDAMA","21","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("32","1","99","TOLEDO","VALDEZ","JOSE ANDRES","C ALDAMA","21","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("33","1","61","TOLEDO","VALDEZ","BERNARDO","C MAZATLANCITO","26","","BARR MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("34","1","2","TOLEDO","VALDEZ","CASIANO","C ALDAMA","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("35","1","99","TOLEDO","VALDEZ","MARIA FELIX","C MAZATLANCITO","12 A","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("36","1","61","TOLEDO","VALDEZ","RODOLFO","C MAZATLANCITO","26","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("37","1","19","TIRADO","RODRIGUEZ","MIGUEL ANTONIO","C ALDAMA","13 B","","","1","1");
INSERT INTO jugadores VALUES("38","1","60","TORRES","ROJAS","MA GUADALUPE","C ALDAMA","38","A","BARR MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("39","1","99","TIRADO","VENEGAS","JOSE","C ALDAMA","31","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("40","1","99","TIRADO","VENEGAS","MIGUEL","C ALDAMA","33","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("41","1","99","OSUNA","LOPEZ","ALICIA","C ALDAMA","27","","BARR MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("42","1","38","VEGA","PARRA","ISMAEL","C LIMITE DE VIA","11","","","1","1");
INSERT INTO jugadores VALUES("43","1","38","VEGA","TIRADO","FERNANDO","C LIMITE","11","","ACAPONETA","1","1");
INSERT INTO jugadores VALUES("44","1","38","VEGA","TIRADO","WILFRIDO","LIMITE DE VIA","11","","","1","1");
INSERT INTO jugadores VALUES("45","1","45","VILLAVICENCIO","CERVANTES","RODRIGO","C LIMITE DE VIA","33","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("46","1","75","VALENZUELA","GARCIA","MARIA ISABEL","C MAZATLANCITO","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("47","1","2","BAHENA","RODRIGUEZ","GASPAR","C ALDAMA","41","","ACAPONETA","1","1");
INSERT INTO jugadores VALUES("48","1","45","VILLA","HERNANDEZ","JUAN","C LIMITE","31","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("49","1","60","VILLAVICENCIO","MEDINA","MARIA APOLONIA","C ALDAMA","40","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("50","1","19","AGUILAR","MORENO","JUAN PABLO","C ABASOLO","16","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("51","1","99","VENEGAS","BULGARA","MARIA ALICIA","C ALDAMA","35","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("52","1","2","VENEGAS","CABRALES","LORENZO","C MERIDA","4","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("53","1","99","VENEGAS","PARRA","ANGELICA MARIA","C ALDAMA","29A","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("54","1","99","VENEGAS","PARRA","EFRAIN","C MERIDA","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("55","1","99","VENEGAS","PARRA","FERNANDO","C MERIDA","1","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("56","1","99","VENEGAS","SILLAS","CELEDONIO","C ALDAMA","35 PTE","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("57","1","99","VENEGAS","SOLIZ","ELVIRA","C MAZATLANCITO","2","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("58","1","99","VENEGAS","SILLAS","NARCISO","C ALDAMA","35","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("59","1","71","VIERA","AGUILAR","MARTIN","C ALDAMA","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("60","1","99","VIERA","CORDOVA","ANTONIO","C MAZATLANCITO","2","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("61","1","61","VIERA","ONTIVERO","SIRINEO","C ABASOLO","SN","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("62","1","61","VIERA","ROMAN","MARIA CONCEPCION","C ABASOLO","SN","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("63","1","71","VIERA","ROMAN","MARTIN","C ALDAMA","SN","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("64","1","71","VIERA","ROMAN","PEDRO","C ALDAMA","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("65","1","99","VIERA","RIVERA","EVARISTO","C MAZATLANCITO","2","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("66","1","99","VIERA","SOTO","CARMEN","C ABASOLO","8PTE","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("67","1","45","VIERA","SOTO","FEDERICO","C ALDAMA","40","","COL MAZATLANCIITO","1","1");
INSERT INTO jugadores VALUES("68","1","99","VIERA","SOTO","FAUSTINO","PROL ABASOLO","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("69","1","29","VERA","VERA","ALICIA","C JUAN ESCUTIA","S/N","","","1","1");
INSERT INTO jugadores VALUES("70","1","20","VAZQUEZ","NORIEGA","MA CONCEPCION","C LA PAZ","3","","ACAPONETA","1","1");
INSERT INTO jugadores VALUES("71","1","38","XX","TORRES","ROSA DEL CARMEN","C LIMITE","17","","","1","1");
INSERT INTO jugadores VALUES("72","1","20","CONTRERAS","CEDANO","ADRIANA BERENICE","C ABASOLO","20","","ACAPONETA","1","1");
INSERT INTO jugadores VALUES("73","1","45","BERMUDEZ","ARIAS","LUCINDA","C ALDAMA","36","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("74","1","29","BARGAS","DE LA CRUZ","FRANCISCO","C JUAN ESCUTIA","9","","","1","1");
INSERT INTO jugadores VALUES("75","1","29","BRIZUELA","DADO","NATIVIDAD","C JUAN ESCUTIA","13","","","1","1");
INSERT INTO jugadores VALUES("76","1","60","BERNAL","GARCIA","JOSE DE JESUS","C ALDAMA","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("77","1","60","BERNAL","GARCIA","SEVERIANO","C ALDAMA","38","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("78","1","18","BERNAL","JIMENEZ","LUCILA","C ALDAMA","S/N","","","1","1");
INSERT INTO jugadores VALUES("79","1","60","BERMUDES","MARTINEZ","VICTOR","C ALDAMA","40 A","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("80","1","45","BERMUDEZ","PINEDA","ESTEBAN","C ALDAMA","36","","ACAPONETA","1","1");
INSERT INTO jugadores VALUES("81","1","19","CAMACHO","ESPINOSA","MARIA","C ALDAMA","11C","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("82","1","61","CAMACHO","FLORES","LUCIA","C MAZATLANCITO","24 A","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("83","1","99","CAMACHO","GUERRERO","LEONARDO","C PROLONGACION ABASOLO","4","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("84","1","99","CAMACHO","LOPEZ","MARTIN","C ABASOLO","4PTE","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("85","1","99","CAMACHO","MORALES","JORGE","C MAZATLANCITO","4 A","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("86","1","2","CONCHAS","BRETADO","MARCIANA","C MERIDA","4","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("87","1","4","CONTRERAS","OSUNA","RAMONA","C MAZATLANCITO","28","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("88","1","99","CRUZ","BORIS","ARMANDO","C ABASOLO","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("89","1","3","CARRILLO","BERUMEN","EMMA","C ALDAMA","44","","ACAPONETA","1","1");
INSERT INTO jugadores VALUES("90","1","38","CARRILLO","BERUMEN","ENRIQUE","C LIMITE DE VIA","17","","","1","1");
INSERT INTO jugadores VALUES("91","1","38","CARRILLO","CASARES","GUILLERMO","C ALDAMA","24","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("92","1","99","CORDOBA","CASTILLO","MARIA DEL REFUGIO","C MAZATLANCITO","2","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("93","1","18","CARRILLO","CASARES","TERESA","C ALDAMA","S N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("94","1","60","CORTEZ","MEJIA","LUZ YOLANDA","C ALDAMA","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("95","1","99","CRUZ","MONTAO","FELIPE","C ABASOLO","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("96","1","29","CRUZ","MONTAO","MARCO ANTONIO","C JUAN ESCUTIA","16","","","1","1");
INSERT INTO jugadores VALUES("97","1","19","DE LA CRUZ","PASTRAN","J MERCED","C ALDAMA","13","","ACAPONETA","1","1");
INSERT INTO jugadores VALUES("98","1","29","DE LA CRUZ","RANGEL","SOTERA","C JUAN ESCUTIA","9","","","1","1");
INSERT INTO jugadores VALUES("99","1","38","CARRILLO","SALAS","MARIA CANDELARIA","ALDAMA","24","","","1","1");
INSERT INTO jugadores VALUES("100","1","45","CASILLAS","RODRIGUEZ","MARIA EUGENIA","C ALDAMA","40","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("101","1","45","CASILLAS","RODRIGUEZ","SOFIA","C ALDAMA PONIENTE","34","","BARR MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("102","1","29","CASTRO","RAMIREZ","BRAULIA","C JUAN ESCUTIA","17","","ACAPONETA","1","1");
INSERT INTO jugadores VALUES("103","1","3","CASTAEDA","ROSALES","ABEL","C ALDAMA","46 B","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("104","1","75","DELGADO","PARRA","MARIA LUISA","C RAYON","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("105","1","38","DERAS","ESCOBEDO","JOSE","C LIMITE DE VIA","9","","","1","1");
INSERT INTO jugadores VALUES("106","1","38","DERAS","OCAMPO","CLAUDIA CELENE","C LIMITE","9","","","1","1");
INSERT INTO jugadores VALUES("107","1","38","DERAS","OCAMPO","LUIS BERNABE","C LIMITE DE VIA","9","","","1","1");
INSERT INTO jugadores VALUES("108","1","38","DERAS","OCAMPO","MARCO ANTONIO","C LIMITE DE VIA","9","","","1","1");
INSERT INTO jugadores VALUES("109","1","19","DIAZ","RUBIO","ROSIO DEL CARMEN","C ALDAMA","11B","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("110","1","19","ESTRADA","MESA","PABLO","C ABASOLO","16PTE","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("111","1","19","FLORES","CEDANO","ELIAS","C ALDAMA","11","D","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("112","1","60","FLORES","CEDANO","MARIA","C ALDAMA","36 A","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("113","1","38","FLORES","LORETO","MARIA DEL PILAR","C LIMITE","31","","ACAPONETA","1","1");
INSERT INTO jugadores VALUES("114","1","19","FLORES","MONTES","ARTURO","C ALDAMA","11B","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("115","1","45","FLORES","MONTES","DAVID","C LIMITE DE VIA","27","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("116","1","18","FLORES","MONTES","GUSTAVO","C ALDAMA","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("117","1","19","FLORES","RODRIGUEZ","HILDA","C ABASOLO","16","","","1","1");
INSERT INTO jugadores VALUES("118","1","2","FLORES","RODRIGUEZ","SERGIO FRANCISCO","C ALDAMA","43","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("119","1","99","FRIAS","CASTRO","MARIA ELENA DE JESUS","C MAZATLANCITO","6 A","E","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("120","1","99","FRIAS","CASTRO","FELICITAS","C MAZATLANCITO","6 A","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("121","1","19","FRAYRE","FLORES","JUAN ANTONIO","C ABASOLO","16","","","1","1");
INSERT INTO jugadores VALUES("122","1","19","FAVELA","GONZALEZ","PEDRO ARCENIO","C ALDAMA","20 C","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("123","1","29","GODINEZ","SALAS","JOSEFINA","C JUAN ESCUTIA","19","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("124","1","60","GALINDO","SILLAS","NATIVIDAD","C ALDAMA","36 B","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("125","1","20","GOMEZ","MURGUIA","GERARDO","C LA PAZ","3","","","1","1");
INSERT INTO jugadores VALUES("126","1","28","GOMEZ","ORTEGA","MARIA LUISA","C LA PAZ","18","","BARRIO EL ESTADIO","1","1");
INSERT INTO jugadores VALUES("127","1","29","GOMEZ","ORTEGA","MARCELINO","C LA PAZ","6","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("128","1","3","GOMEZ","PARTIDA","MARIA MAGDALENA","C ALDAMA","50","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("129","1","18","GOMEZ","VILLA","OTILIA","C ALDAMA PONIENTE","18 I","","","1","1");
INSERT INTO jugadores VALUES("130","1","20","GOMEZ","VAZQUEZ","GERARDO RAMON","C LA PAZ","3","","","1","1");
INSERT INTO jugadores VALUES("131","1","29","GONZALEZ","GUZMAN","GONZALO","C LA PAZ","6","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("132","1","29","GONZALEZ","MENDOZA","NORBERTO","C LA PAZ","6","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("133","1","61","GONZALEZ","RODRIGUEZ","FELIPE","C MAZATLANCITO","24 A","","BARRIO MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("134","1","99","GONZALEZ","VILLELA","OLIVIA","C MAZATLANCITO","4A","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("135","1","19","GONZALEZ","ZALAZAR","OTILIA","C LA PAZ","S/N","","","1","1");
INSERT INTO jugadores VALUES("136","1","61","GUARDADO","GARCIA","EVERARDO","C ABASOLO","9","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("137","1","29","GUARDADO","GARCIA","MARIA","C JUAN ESCUTIA","17","","","1","1");
INSERT INTO jugadores VALUES("138","1","2","GARZON","LOPEZ","FELICITAS","C ALDAMA","39 A","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("139","1","60","GARCIA","MILLAN","MARIA LUISA","C ALDAMA","38","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("140","1","60","GARZON","SEGURA","PAZ","C LIMITE","37","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("141","1","2","GARCIA","VELAZQUEZ","JOSE DAVID","C ALDAMA","43 PTE","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("142","1","3","GUTIERREZ","LOPEZ","ALFREDO","C ALDAMA","48","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("143","1","71","GUTIERREZ","LOPEZ","MARIA DOLORES","C ALDAMA","SN","","","1","1");
INSERT INTO jugadores VALUES("144","1","71","GUTIERREZ","LOPEZ","NORMA ANGELICA","C ALDAMA","49","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("145","1","71","GUTIERREZ","LOPEZ","SALVADOR","C ALDAMA","49","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("146","1","71","GUTIERREZ","RAMIREZ","ANTONIO","C ALDAMA","49","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("147","1","61","GUZMAN","ARIAS","ANGEL","C MAZATLANCITO","22","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("148","1","99","GUZMAN","PARDO","JUAN","C ABASOLO","8 PTE","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("149","1","99","GUZMAN","PARDO","VICTORIANO","C MAZATLANCITO","6A","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("150","1","61","GUZMAN","VIERA","EMILIO","C MAZATLANCITO","20","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("151","1","99","GUZMAN","VIERA","GUADALUPE","C ABASOLO","8PTE","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("152","1","75","HERNANDEZ","DIAZ","J SANTOS","C MAZATLANCITO","30","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("153","1","19","HERNANDEZ","ESPERICUETA","MARTINA","C ALDAMA","13","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("154","1","99","DE HARO","GOMEZ","FELICITAS","C ALDAMA","31","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("155","1","38","HERNANDEZ","RANGEL","ARMIDA","C ALDAMA","26","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("156","1","71","HERNANDEZ","SANCHEZ","PAULA","C ALDAMA","47","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("157","1","61","ZAMARRIPA","LEMUS","OLGA","PROL ABASOLO","1","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("158","1","99","LOPEZ","ALATORRE","HIPOLITA","C ALDAMA","27PTE","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("159","1","2","LOPEZ","BULGARA","EPIGMENIA","C ALDAMA","43","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("160","1","38","LOPEZ","CARRILLO","ALFONSO","C LIMITE","15","","","1","1");
INSERT INTO jugadores VALUES("161","1","29","LOPEZ","GUARDADO","AMADA","C JUAN ESCUTIA","17","","","1","1");
INSERT INTO jugadores VALUES("162","1","99","LOPEZ","LOPEZ","FRANCISCA","C PROLONGACION ABASOLO","4","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("163","1","28","LOPEZ","LOPEZ","LUIS ANTONIO","C ALDAMA","19","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("164","1","19","LOPEZ","LOPEZ","ORALIA","C ALDAMA","13B","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("165","1","2","LOPEZ","PEREZ","ROBERTO","C ALDAMA","41 A","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("166","1","3","LOPEZ","SALAS","ALEJANDRO","C ALDAMA","46","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("167","1","2","LOPEZ","SALAS","ANPELIA","C ABASOLO","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("168","1","71","LOPEZ","SALAS","MARIA ELENA","C ALDAMA","49","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("169","1","61","LOZANO","MALDONADO","CONSEPCION","C MAZATLANCITO","20","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("170","1","45","MEDINA","ALVAREZ","MARIA DEL ROSARIO","C ALDAMA","32","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("171","1","45","MEDINA","CRISTOBAL","TOMASA","C LIMITE","33","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("172","1","99","MEDINA","HERRERA","CONCEPCION","C ALDAMA","21PTE","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("173","1","28","MEDINA","ROMERO","MARIA DEL CARMEN","C ALDAMA","19","","BARR ESTADIO","1","1");
INSERT INTO jugadores VALUES("174","1","61","MALDONADO","GUARDADO","CONSUELO","C RAYON","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("175","1","61","MALDONADO","MAYORQUIN","MERCEDES","C MAZATLANCITO","26","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("176","1","99","MALDONADO","UREA","JULIO","C MAZATLANCITO","4","","BARR MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("177","1","71","MALDONADO","UREA","JUAN","C ALDAMA","47","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("178","1","29","MENDOZA","ORTEGA","PORFIRIA","C LA PAZ","6","","","1","1");
INSERT INTO jugadores VALUES("179","1","19","MONTES","RODRIGUEZ","MA MAGDALENA","C ALDAMA","11","D","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("180","1","99","CASILLAS","MURILLO","J JESUS","C MAZATLANCITO","10","","BARR MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("181","1","71","MORA","FERTO","ROSA ODULIA","C ALDAMA","78","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("182","1","19","MARTINEZ","HERNANDEZ","JOSEFINA","C ALDAMA","13","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("183","1","75","MORENO","JULIO","FRANCISCO","C SIN NOMBRE","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("184","1","19","MORENO","MADERA","JUANA","C ABASOLO","16A","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("185","1","19","MORENO","LERMA","JOSE","C ALDAMA","11C","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("186","1","45","MARMACEDA","PARTIDA","DAVID","C ALDAMA PONIENTE","34","","BARR DE MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("187","1","99","MAYORQUIN","DIAZ","LAURA ELENA","C ALDAMA","25A","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("188","1","61","MAYORQUIN","ORTIZ","HECTOR MANUEL","C MAZATLANCITO","26","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("189","1","2","MAYORQUIN","PONCE","SERGIO ARMANDO","C ALDAMA","41 A","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("190","1","2","MAYORQUIN","SILVA","AURELIO","C MATAMOROS","5","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("191","1","99","MAYORQUIN","SILVA","MARIA","C MAZATLANCITO","4","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("192","1","29","NAJERA","GARCIA","CELSO","C JUAN ESCUTIA","9","","","1","1");
INSERT INTO jugadores VALUES("193","1","19","NORIEGA","MARTINEZ","JOSE CARLOS","C ALDAMA","13","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("194","1","19","NORIEGA","MARTINEZ","JOSE RICARDO","C ALDAMA","13","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("195","1","60","GARZON","SANCHEZ","JOSE ISABEL","C LIMITE","37","","BARR MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("196","1","38","OCAMPO","MENDOZA","MARIA","C LIMITE DE VIA","9","","","1","1");
INSERT INTO jugadores VALUES("197","1","2","ONTIVEROS","CASTAEDA","GREGORIO","C ALDAMA","39 A","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("198","1","2","ONTIBEROS","GARZON","LORENA CANDELARIA","C ALDAMA","39 A","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("199","1","61","ORNELAS","FLORES","RAMON","PROL ABASOLO","1","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("200","1","19","ORTEGA","QUIONES","EULOGIA","C AMERICA","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("201","1","29","ORTEGA","RODRIGUEZ","TIBURCIO","C JUAN ESCUTIA","12","","","1","1");
INSERT INTO jugadores VALUES("202","1","3","ORTIZ","RODRIGUEZ","TEODORO","C ALDAMA","50","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("203","1","99","GOMEZ","FLORES","MIGUEL ALBERTO","C MAZATLANCITO","6 A","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("204","1","4","OSUNA","ASTORGA","ALEJANDRA","C MAZATLANCITO","28","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("205","1","75","PALAFOX","PADILLA","JOSE ANGEL","C SIN NOMBRE","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("206","1","75","PALAFOX","PADILLA","ESEQUIEL","C SIN NOMBRE","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("207","1","2","PEREZ","AVALOS","JOSE DE JESUS","C","0","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("208","1","99","PARTIDA","AVILA","PEDRO","C ALDAMA","23","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("209","1","61","PARTIDA","CONTRERAS","RAFAELA","C PROL ABASOLO","3","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("210","1","2","PEREZ","CRUZ","MARIANO","C MATAMOROS","7","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("211","1","99","PARRA","FLORES","ANDREA","C MERIDA","1","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("212","1","2","PEREZ","FLORES","ESPERANZA","C ALDAMA","41 A","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("213","1","2","PARTIDA","LOPEZ","ALEJANDRINA","C ABASOLO","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("214","1","99","PERALTA","LOPEZ","MARIA GUADALUPE","C ALDAMA","27","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("215","1","99","PARTIDA","MAYORQUIN","LAURA LETICIA","C ALDAMA","25 A","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("216","1","99","PERALTA","LOPEZ","JOSE MARTIN","C ALDAMA","27","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("217","1","61","PARTIDA","NAVA","BASILIO","PROL ABASOLO PONIENTE","3","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("218","1","99","PARTIDA","ROSALES","HUMBERTO","C ALDAMA PONIENTE","25","","BARRIO EL MAZATIANCITO","1","1");
INSERT INTO jugadores VALUES("219","1","2","PARTIDA","SALAS","GUADALUPE","C ALDAMA","39 PTE","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("220","1","99","PARTIDA","ZAMORA","JOSE CARLOS","C ALDAMA","23PTE","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("221","1","99","PARTIDA","ZAMORA","DAVID","C ALDAMA","23","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("222","1","3","RODRIGUEZ","ALATORRE","JUAN MANUEL","C ALDAMA","42","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("223","1","45","RODRIGUEZ","CAZARES","SIMON","C MAZATLANCITO","8","","BARR MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("224","1","45","RODRIGUEZ","FLORES","RAMONA","C LIMITE DE FERROCARRIL","35","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("225","1","18","RODRIGUEZ","GOMEZ","DIANA EUGENIA","C ALDAMA","18 I PTE","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("226","1","38","RODRIGUEZ","CARRILLO","MARIA DE LOS ANGELES","C ALDAMA","20","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("227","1","18","RODRIGUEZ","GOMEZ","HECTOR MANUEL","C ALDAMA","18 I","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("228","1","38","RODRIGUEZ","CARRILLO","MARIA DE JESUS","C ALDAMA","20","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("229","1","75","RODRIGUEZ","PIA","JUAN ENRIQUE","C RAYON","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("230","1","2","RODRIGUEZ","PARRA","MARIA AIDA","C ALDAMA","41","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("231","1","3","RODRIGUEZ","PARRA","EVELIA","C ALDAMA","48","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("232","1","99","RODRIGUEZ","SALDAA","MARIA GUADALUPE","PROL ABASOLO","24","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("233","1","2","RODRIGUEZ","PARRA","IGNACIA","C ALDAMA","41 PTE","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("234","1","99","RODRIGUEZ","SALDAA","RAFAEL","C MAZATLANCITO","12A","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("235","1","99","RODRIGUEZ","TAPIA","DANIEL","C MAZATLANCITO","12","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("236","1","99","RODRIGUEZ","TORRES","PAULA","C ABASOLO","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("237","1","18","RODRIGUEZ","VILLELA","ALEJANDRO","C ALDAMA","18 I PTE","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("238","1","38","RODRIGUEZ","VALENCIA","PEDRO","C ALDAMA","20","","","1","1");
INSERT INTO jugadores VALUES("239","1","3","RODRIGUEZ","REYES","JESUS","C ALDAMA","42","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("240","1","2","RODRIGUEZ","REYES","MARIA","C ALDAMA","37 PTE","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("241","1","71","RAMIREZ","AVENA","JUSTINO","C ALDAMA","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("242","1","61","RAMIREZ","AVENA","ROSARIO","C ABASOLO","9","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("243","1","38","RAMIREZ","GUTIERREZ","SILVIA ELVIRA","C ALDAMA","22","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("244","1","19","ROMERO","DE LEON","JUAN","C AMERICA","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("245","1","61","RAMOS","MALDONADO","JULIO","C RAYON","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("246","1","19","ROMERO","ORTEGA","MAURA ELENA","C ABASOLO","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("247","1","71","RAMIREZ","PEREZ","MAXIMINA","C MATAMOROS","45","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("248","1","71","RAMOS","DE LA ROSA","JESUS","C ALDAMA","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("249","1","71","RAMIREZ","ZARAVIA","SIMON","C ALDAMA","SN","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("250","1","61","GUZMAN","PARDO","FLORENTINO","C MAZATLANCITO","22","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("251","1","29","RENDON","RODRIGUEZ","MARIA GUADALUPE","C JUAN ESCUTIA","16","","","1","1");
INSERT INTO jugadores VALUES("252","1","45","RIOS","RAMIREZ","DANIEL","C ALDAMA","38","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("253","1","38","RIVERA","REYES","MARIA DEL CARMEN","C LIMITE","15","","","1","1");
INSERT INTO jugadores VALUES("254","1","45","RIVERA","REYES","MARTIN","C LIMITE","29","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("255","1","45","RIVERA","SOTO","RAMON","C ALDAMA","30 A","","","1","1");
INSERT INTO jugadores VALUES("256","1","75","RAYGOZA","GONZALEZ","TRANQUILINA","PROL GUADALAJARA","1","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("257","1","99","SALAZAR","CONCHAS","PAULA NATIVIDAD","C MAZATLANCITO","2","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("258","1","18","SILVA","CARRILLO","JOSE ANTONIO","C ALDAMA","S/N","","","1","1");
INSERT INTO jugadores VALUES("259","1","38","SILVA","CARRILLO","FERMIN","C ALDAMA","22","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("260","1","18","SILVA","CARRILLO","ROSAURA","C ALDAMA","S/N","","","1","1");
INSERT INTO jugadores VALUES("261","1","61","SALAS","ARROYO","CAMILA","C SIN NOMBRE","S.N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("262","1","2","SOLIS","HERRERA","MARIA LUCILA","C MERIDA","4","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("263","1","38","SALAS","LOPEZ","MARIA DEL CARMEN","C ALDAMA","24","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("264","1","18","SILVA","MARTINES","JOSE","C ALDAMA","68","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("265","1","20","SOLIS","MAYORQUIN","RICARDA","C LA PAZ","7","","BARR LA CAPILLA","1","1");
INSERT INTO jugadores VALUES("266","1","99","SILLAS","PARRA","MELQUIADES","C ALDAMA","35 PTE","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("267","1","60","SANCHEZ","AVENA","GILBERTO","C ALDAMA","36 B","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("268","1","60","SANCHEZ","AVENA","MANUEL","C ALDAMA","38 A","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("269","1","75","SALAZAR","VENEGAS","JESUS","PROL GUADALAJARA","3","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("270","1","29","SANCHEZ","DE LA PAZ","EGRISELDA","C JUAN ESCUTIA","11","","COL EL ESTADIO","1","1");
INSERT INTO jugadores VALUES("271","1","29","GAMEROS","MUIZ","SOELIA MARGARITA","C JUAN ESCUTIA","19","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("272","1","99","PARTIDA","AVILA","CLARO","C ALDAMA","25","","BARR DE MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("273","1","38","RODRIGUEZ","CARRILLO","JESUS ERNESTO","C ALDAMA","20","","BARR DE MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("274","1","19","ESTRADA","FLORES","GONZALO","C ABASOLO","16","","BARR DEL ESTADIO","1","1");
INSERT INTO jugadores VALUES("275","1","75","HERNANDEZ","RANGEL","HERNESTINA","C MAZATLANCITO","30","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("276","1","61","CONTRERAS","GARCIA","OFELIA","PROL ABASOLO","3","","BARR DE MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("277","1","19","PACHECO","NAVA","RUTH MIREYA","C ALDAMA PONIENTE","13","","BARR MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("278","1","4","CONTRERAS","ASTORGA","ANTONIO","C MAZATLANCITO","28","","BARR MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("279","1","38","SILVA","CARRILLO","VICTOR MANUEL","C ALDAMA Y JUAN ESCUTIA","S/N","","COL ACAPONETA","1","1");
INSERT INTO jugadores VALUES("280","1","2","LOPEZ","PEREZ","MARTHA BEATRIZ","C ALDAMA PONIENTE","41","A","BARR DE MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("281","1","2","BAHENA","RODRIGUEZ","CARLOS FERNANDO","C ALDAMA PONIENTE","41","A","BARR EL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("282","1","99","VIERA","CORDOVA","ENRIQUE GASPAR","C MAZATLANCITO","2","","BARR DE MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("283","1","29","ORTEGA","QUIONES","MARIO","C JUAN ESCUTIA","11","B","ACAPONETA","1","1");
INSERT INTO jugadores VALUES("284","1","28","BURCIAGA","DE LA PAZ","ESTEBAN","C ALDAMA","15","","BARR LA ESTACION","1","1");
INSERT INTO jugadores VALUES("285","1","71","ALVALLE","SOLIS","MARTINA","C ALDAMA","S/N","","BARR MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("286","1","99","MALDONADO","MAYORQUIN","MARIA OFELIA","C MAZATLANCITO NORTE","4","","BARR DE MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("287","1","20","CASTAEDA","DE LEON","EUGENIO","C ABASOLO Y AMERICA","S/N","","ACAPONETA","1","1");
INSERT INTO jugadores VALUES("288","1","3","MORA","SALAS","GILBERTO","C ALDAMA","44 B","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("289","1","99","VENEGAS","PARRA","ABRAHAM","C MERIDA","1","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("290","1","28","LOPEZ","SANCHEZ","ALICIA","C ALDAMA Y JUAN ESCUTIA","S/N","","ACAPONETA","1","1");
INSERT INTO jugadores VALUES("291","1","29","CAMARGO","GONZALEZ","MARIA CRISTINA","C LA PAZ NORTE","5","B","BARR DE MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("292","1","29","MENDEZ","CAMACHO","HUMBERTO","C JUAN ESCUTIA NORTE","7","","ACAPONETA","1","1");
INSERT INTO jugadores VALUES("293","1","29","PEREZ","CONTRERAS","CARMEN","C LA PAZ","S/N","","ACAPONETA","1","1");
INSERT INTO jugadores VALUES("294","1","99","ESTRADA","MONTERO","MARIA DEL SOCORRO","C ALDAMA","29","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("295","1","3","PEREZ","CECEA","IGNACIO","C ALDAMA","46 B","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("296","1","99","CONTRERAS","GALLEGOS","MARTINA","C ALDAMA","23","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("297","1","29","LOPEZ","LOPEZ","RAMON","C ABASOLO Y JUAN ESCUTIA","S/N","","ACAPONETA","1","1");
INSERT INTO jugadores VALUES("298","1","29","ORTEGA","SANCHEZ","GRICELDA","C JUAN ESCUTIA","11","A","ACAPONETA","1","1");
INSERT INTO jugadores VALUES("299","1","61","LOPEZ","SALAS","SABAS","C MAZATLANCITO","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("300","1","60","SANCHEZ","GALINDO","ALMA MONICA","C ALDAMA PONIENTE","36","B","ACAPONETA","1","1");
INSERT INTO jugadores VALUES("301","1","99","RODRIGUEZ","PARTIDA","TEODORA","C MAZATLANCITO","12","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("302","1","2","GONZALEZ","HERRERA","ERNESTO","C ABASOLO PONIENTE","5","","ACAPONETA","1","1");
INSERT INTO jugadores VALUES("303","1","29","MENDOZA","ORTEGA","MARTHA","C JUAN ESCUTIA NORTE","11","","ACAPONETA","1","1");
INSERT INTO jugadores VALUES("304","1","99","CASILLAS","RODRIGUEZ","ALEJANDRO","C MAZATLANCITO","8","","BARR MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("305","1","60","RUBIO","RAMIREZ","LORENA BEATRIZ","C ALDAMA PONIENTE","36","","ACAPONETA","1","1");
INSERT INTO jugadores VALUES("306","1","18","ARENA","XX","CASIMIRA","C LIMITE","22","","ZONA CENTRO","1","1");
INSERT INTO jugadores VALUES("307","1","29","LOPEZ","GUARDADO","JESUS MANUEL","C JUAN ESCUTIA","17","","ACAPONETA","1","1");
INSERT INTO jugadores VALUES("308","1","61","LEMUS","JUAREZ","FLORENTINA","C PROL ABASOLO","1","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("309","1","99","MORENO","RODRIGUEZ","SARA","C MAZANTLACITO","8","","ACAPONETA","1","1");
INSERT INTO jugadores VALUES("310","1","61","GUZMAN","PARDO","SECUNDINO","C MAZATLANCITO NORTE","22","","BARR MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("311","1","2","OLIVAS","RODRIGUEZ","MARIA DOLORES","U HAB MILITAR","12","","LAS MOJONERAS","1","1");
INSERT INTO jugadores VALUES("312","1","29","PACHECO","FERNANDEZ","ABEL","C ABASOLO","11","","BARR MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("313","1","99","SALAZAR","SALAZAR","FRANCISCA","C MAZATLANCITO","22","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("314","1","61","PEREZ","HERNANDEZ","JOSE DE JESUS","C MAZATLANCITO","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("315","1","61","RAMIREZ","AVENA","ALEJANDRA","PROL ABASOLO","12","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("316","1","2","VENEGAS","CONCHAS","LUIS ALBERTO","C MERIDA","4","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("317","1","19","ESPINOZA","HERNANDEZ","JUAN MANUEL","C ALDAMA","13 PTE.","","BARR EL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("318","1","99","BELTRAN","VIERA","JOSE HILIBERTO","C PROL ABASOLO","S/N","","BARR MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("319","1","2","SOTO","PARTIDA","CARLOS ALBERTO","C ALDAMA","39","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("320","1","38","HERRERA","CEDANO","LUCILA","C LIMITE","13","","ACAPONETA","1","1");
INSERT INTO jugadores VALUES("321","1","60","ROMERO","CASTILLO","FERNANDO","C LIMITE","S/N","","ACAPONETA","1","1");
INSERT INTO jugadores VALUES("322","1","20","GONZALEZ","MENDOZA","ANA LILIANA","C LA PAZ","1","","ACAPONETA","1","1");
INSERT INTO jugadores VALUES("323","1","2","REYES","MAYORQUIN","GRISELDA","C ALDAMA","29 C","","BARR MAZATANCLITO","1","1");
INSERT INTO jugadores VALUES("324","1","75","SANTIAGO","RAYGOZA","EREYDA TOMASA","PROL GUADALAJARA","1","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("325","1","75","CRISTO","MONTIEL","GERARDO","C MAZATLANCITO","S/N","","BARR MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("326","1","75","FLORES","MONTIEL","MARIA NATIVIDAD","C MAZATLANCITO","S/N","","BARR MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("327","1","18","GALLARDO","ANDALON","JOSE","C ALDAMA","19","","ACAPONETA","1","1");
INSERT INTO jugadores VALUES("328","1","28","RAMIREZ","GUTIERREZ","PEDRO AGUSTIN","C ALDAMA","17 PTE","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("329","1","19","MAYORQUIN","RIOS","GREGORIO","C AMERICA","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("330","1","19","AGUILAR","MORENO","IRMA EVELIA","C ABASOLO","16","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("331","1","19","AGUILAR","MORENO","AURORA FABIOLA","C ABASOLO","16","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("332","1","99","BURGUEO","VENEGAS","JOSE GUADALUPE","C ALDAMA","35","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("333","1","38","DERAS","OCAMPO","VICTOR JAVIER","C LIMITE","9","","BARR LA ESTACION","1","1");
INSERT INTO jugadores VALUES("334","1","2","VENEGAS","CONCHAS","ADRIAN","C MERIDA","4","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("335","1","38","ELIAS","VALDIVIA","GEORGINA","C ALDAMA","20","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("336","1","29","HERNANDEZ","BRIZUELA","CELIA YADIRA","C JUAN ESCUTIA","13","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("337","1","29","NAJERA","DE LA CRUZ","ABEL","C JUAN ESCUTIA","9","","BARR EL ESTADIO","1","1");
INSERT INTO jugadores VALUES("338","1","61","GUZMAN","LOZANO","ZULMA HAYDEE","C MAZATLANCITO","20","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("339","1","61","BALTAZAR","VIERA","FRANCI VIRGINIA","PROL ABASOLO","12","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("340","1","61","GUARDADO","GARCIA","JOSE","PROL ABASOLO","12","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("341","1","60","FLORES","LORA","PETRA","C ALDAMA","40 B","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("342","1","99","PARTIDA","ZAMORA","GUILLERMO","C ALDAMA","23","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("343","1","45","MARTINEZ","RODRIGUEZ","NORMA ANGELICA","PROL ABASOLO","12","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("344","1","60","GUZMAN","LOZANO","RUTH MARIBEL","C ALDAMA","36","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("345","1","99","RODRIGUEZ","PARTIDA","ESTHELA","C MAZATLANCITO","12","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("346","1","75","BETANCOURT","GUERRERO","VICTOR EVERARDO","C MAZATLANCITO","9","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("347","1","29","NAVARRO","INDAS","MARIA GUADALUPE","C LA PAZ","S/N","","COL FERROCARRILERA","1","1");
INSERT INTO jugadores VALUES("348","1","29","SANCHEZ","ORTEGA","GRICELDA","C JUAN ESCUTIA","11 A","","BARR EL ESTADIO","1","1");
INSERT INTO jugadores VALUES("349","1","3","GUARDADO","GARCIA","ANGELA","C ALDAMA","46 B","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("350","1","2","VENEGAS","CONCHAS","JUAN CARLOS","C MERIDA","4","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("351","1","99","AGUILAR","RODRIGUEZ","MARICELA","C ALDAMA","23","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("352","1","2","TOLEDO","BERNAL","LUIS YAIRSINI","C ALDAMA","37","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("353","1","99","ESPERICUETA","VENEGAS","JOSE ALFREDO","C ALDAMA","35","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("354","1","71","BLANCO","ALVALLE","BLANCA JAZMIN","PROL ALDAMA","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("355","1","20","ALVALLE","SOLIS","ADELA","C LA PAZ","7","","BARR EL ESTADIO","1","1");
INSERT INTO jugadores VALUES("356","1","20","ALVALLE","SOLIS","ISRAEL","C LA PAZ","7","","BARRIO LA CAPILLA","1","1");
INSERT INTO jugadores VALUES("357","1","29","GOMEZ","ORTEGA","GREGORIA","C ABASOLO","S/N","","ACAPONETA","1","1");
INSERT INTO jugadores VALUES("358","1","38","TORRES","ESPAA","ADELAIDA","C LIMITE","17","","ACAPONETA","1","1");
INSERT INTO jugadores VALUES("359","1","2","SOTO","PARTIDA","GABRIELA","C ALDAMA","39","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("360","1","60","NUEZ","PUENTES","CESAR","C ALDAMA","34","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("361","1","99","MENDOZA","AYALA","CANDIDA","C MAZATLANCITO","10","","BARR MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("362","1","71","ALVALLE","SOLIS","MIGUEL ANGEL","PROL ALDAMA","S/N","","BARR MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("363","1","71","MALDONADO","HERNANDEZ","GUILLERMINA DE JESUS","C ALDAMA","47","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("364","1","60","VILLAVICENCIO","MEDINA","LUZ ELENA","C ALDAMA","40","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("365","1","28","BURCIAGA","ALCARAZ","ESTEBAN","C ALDAMA","15","","ACAPONETA","1","1");
INSERT INTO jugadores VALUES("366","1","61","TORRES","MORENO","IRMA YOLANDA","C RAYON","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("367","1","29","ANDRADE","ORTIZ","MARIA DE JESUS","C JUAN ESCUTIA","9","","ACAPONETA","1","1");
INSERT INTO jugadores VALUES("368","1","99","CASILLAS","CAMPOS","SERGIO","C MAZATLANCITO","8","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("369","1","3","MORA","SALAS","PORFIRIO","C ALDAMA","44 B","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("370","1","61","VIERA","SOTO","JOSE MANUEL","PROL ABASOLO","11","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("371","1","71","VIERA","MORA","JOSE GUADALUPE","PROL ALDAMA","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("372","1","71","VIERA","ROMAN","JORGE ANTONIO","PROL ALDAMA","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("373","1","99","CAMACHO","LOPEZ","MARIA RAQUEL","PROL ABASOLO","4","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("374","1","61","VIERA","XX","MICAELA","C MAZATLANCITO","20","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("375","1","71","GUTIERREZ","LOPEZ","MARCOS AGUSTIN","PROL ALDAMA","49","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("376","1","71","GARZON","PALOMARES","MARTHA","PROL ALDAMA","49","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("377","1","75","GARCIA","PEREZ","CARLOS ALBERTO","PROL GUADALAJARA","3","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("378","1","19","HERNANDEZ","ALVAREZ","MICAELA","C ALDAMA","13","","BARRIO MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("379","1","99","TOLEDO","MEDINA","JOSE ANDRES","C ALDAMA","21","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("380","1","4","CONTRERAS","OSUNA","MARICELA","C MAZATLANCITO","28","","BARR MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("381","1","3","VILLA","RAMOS","MARIA BLAS","C ALDAMA","42","","BARRIO MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("382","1","75","CRISTO","FLOREZ","JUAN","C MAZATLANCITO","S/N","","BARRIO MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("383","1","19","ESPINOZA","CERDA","SAVINO","C ALDAMA","13","","BARR MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("384","1","99","VENEGAS","SOLIS","JUAN RAMON","C ALDAMA","35","","BARR MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("385","1","2","TOLEDO","BERNAL","YESSICA JASIVE","C ALDAMA","37","","BARRIO MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("386","1","2","ONTIVEROS","GARZON","DALIA VERONICA","C ALDAMA","39 A","","BARRIO MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("387","1","75","CRISTO","FLORES","EUGENIO","C MAZATLANCITO","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("388","1","99","ACOSTA","LOPEZ","KARINA JAZMIN","C ALDAMA","39","","BARRIO MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("389","1","75","RODRIGUEZ","JUAREZ","OLIVIA","C MAZATLANCITO","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("390","1","99","PARTIDA","ROSALES","MARIA DE LOS ANGELES","C ALDAMA","25","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("391","1","61","ORNELAS","ZAMARRIPA","RAMON","PROL ABASOLO","1","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("392","1","60","SANCHEZ","GALINDO","VIOLETA KARINA","C ALDAMA","36 B","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("393","1","4","DE LA CRUZ","ZEPEDA","OLIVIA","C SIN NOMBRE","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("394","1","28","GASTELO","VILLANUEVA","FLORENTINO","C ALDAMA","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("395","1","2","ONTIVEROS","GARZON","SERGIO VALENTIN","C ALDAMA","39 A","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("396","1","28","NEGRETE","TREJO","BEATRIZ","C ALDAMA","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("397","1","99","VENEGAS","BURGARA","BLANCA ESTHELA","C ALDAMA","35","","BARR MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("398","1","38","DOMINGUEZ","AVILA","JUAQUINA","C ALDAMA","28","","ACAPONETA","1","1");
INSERT INTO jugadores VALUES("399","1","38","DOMINGUEZ","AVILA","SAMUEL","C ALDAMA","28","","ACAPONETA","1","1");
INSERT INTO jugadores VALUES("400","1","75","BELTRAN","DELGADO","CESARIO","C MAZATLANCITO","89 B","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("401","1","2","VENEGAS","SOLIS","EFREN","C MERIDA","4","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("402","1","99","VENEGAS","SILLAS","BERTHA MARGARITA","C ALDAMA","35","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("403","1","71","BLANCO","ALVALLE","JUAN ERNESTO","C LIMITE","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("404","1","71","VIERA","ROMAN","VICTOR","PROL ALDAMA","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("405","1","61","VIERA","LOPEZ","MARIA ISIDRA","PROL ABASOLO","3","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("406","1","29","ESTRADA","FLORES","MARIA DEL CARMEN","C JUAN ESCUTIA","S/N","","BARR EL ESTADIO","1","1");
INSERT INTO jugadores VALUES("407","1","71","BIERA","MORA","LAURA MARIA","C ALDAMA","78","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("408","1","61","FELIX","AROS","MARTIN","C MAZATLANCITO","28","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("409","1","3","RODRIGUEZ","ALATORRE","DIANA","C ALDAMA","42","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("410","1","18","MEDINA","MUOZ","ANGELICA","C ALDAMA","11","","LOC ACAPONETA","1","1");
INSERT INTO jugadores VALUES("411","1","29","NAJAR","DE LA CRUZ","ARMANDO","C JUAN ESCUTIA","9","","BARR MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("412","1","71","BLANCO","ALVALLE","MARTHA EUGENIA","C LIMITE","174","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("413","1","0","RAMIREZ","SALAZAR","ANTONIO","PROL GUADALAJARA","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("414","1","61","ORNELAS","ZAMARRIPA","LUCILA","PROL ABASOLO","1","","COL MAZATLANCINTO","1","1");
INSERT INTO jugadores VALUES("415","1","99","VIERA","SOTO","CALIXTRA","PROL ABASOLO","8","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("416","1","20","GOMEZ","VAZQUEZ","JAVIER EFRAIN","C LA PAZ","3","","BARR CUARTEL QUINTO","1","1");
INSERT INTO jugadores VALUES("417","1","60","JUAREZ","FLORES","MARIA EUGENIA","C ALDAMA","40","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("418","1","60","VILLAVICENCIO","MEDINA","TERESA","C ALDAMA","40","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("419","1","75","PEREZ","DOMINGUEZ","MARIA DEL SOCORRO","PROL GUADALAJARA","3","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("420","1","75","GARCIA","PEREZ","DORA JAZMIN","PROL GUADALAJARA","3","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("421","1","99","VENEGAS","BURGARA","ZORAIDA","C ALDAMA","35","","BARR MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("422","1","2","SOTO","PARTIDA","DELIA CONCEPCION","C ALDAMA","39","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("423","1","61","ORNELAS","ZAMARRIPA","MIGUEL ANGEL","PROL ABASOLO","1","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("424","1","19","ROMERO","ORTEGA","JUANA","C ALDAMA","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("425","1","19","SANCHEZ","LOZANO","MARIA OLIVA","C AMERICA","S/N","","BARR EL ESTADIO","1","1");
INSERT INTO jugadores VALUES("426","1","38","CARRILLO","TORRES","ENRIQUE ANIBAL","C LIMITE","17","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("427","1","61","GARCIA","ZATARAIN","ADOLFA MARIA","C RAYON","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("428","1","2","ONTIVEROS","GARZON","ZORAIDA GUADALUPE","C ALDAMA","39","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("429","1","99","CAMACHO","LOPEZ","BLANCA BEATRIZ","PROL ABASOLO","4","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("430","1","99","ESPERICUETA","VENEGAS","MARIA ISABEL","C ALDAMA","35","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("431","1","2","GARZON","RODRIGUEZ","SONIA ERENDIRA","C ALDAMA","39","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("432","1","29","VILLAGRANA","MALDONADO","YENNI ANAHI","C LA PAZ","6","","COL EL ESTADIO","1","1");
INSERT INTO jugadores VALUES("433","1","29","GONZALEZ","MENDOZA","JESUS ABEL","C LA PAZ","6","","COL EL ESTADIO","1","1");
INSERT INTO jugadores VALUES("434","1","38","SILVA","RAMIREZ","LEYLIANY LORELY","C ALDAMA","22","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("435","1","60","SANCHEZ","GALINDO","OSCAR RENE","C ALDAMA","36 B","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("436","1","3","PEREZ","GUARDADO","INES","C ALDAMA","46 B","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("437","1","28","GOMEZ","MEDINA","CELESTINO","C LA PAZ","18","","BARR EL ESTADIO","1","1");
INSERT INTO jugadores VALUES("438","1","61","CONTRERAS","ALEMAN","IRENE","PROL ABASOLO","3","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("439","1","38","DOMINGUEZ","AVILA","SARAHI","C ALDAMA","28","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("440","1","19","SANCHEZ","FLORES","JESUS ELIAS","C ALDAMA","11 D","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("441","1","3","GUTIERREZ","RODRIGUEZ","CHRISTIAN ALFREDO","C ALDAMA","48","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("442","1","28","OSUNA","GOMEZ","SERGIO LUIS","C LA PAZ","18","","BARR EL ESTADIO","1","1");
INSERT INTO jugadores VALUES("443","1","45","RIVERA","RODRIGUEZ","CARLOS LEIBNITZ","C ALDAMA","30","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("444","1","38","REYES","ROCHIN","NOLBERTA","C LIMITE","7","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("445","1","61","MENDEZ","PARTIDA","CARMEN GRISELDA","PROL ABASOLO","49","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("446","1","99","TAPIA","ZARCO","J SOCORRO","PROL ABASOLO","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("447","1","99","PARTIDA","MAYORQUIN","WENDY MAGALI","C ALDAMA","25","","BARR MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("448","1","19","ESTRADA","FLORES","ERIKA YESENIA","C ABASOLO","16","","BARR EL ESTADIO","1","1");
INSERT INTO jugadores VALUES("449","1","45","MARMACEDA","CASILLAS","VERONICA LETICIA","C ALDAMA","34","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("450","1","28","BURCIAGA","ALCARAZ","JUAN PABLO","C ALDAMA","15","","COL EL ESTADIO","1","1");
INSERT INTO jugadores VALUES("451","1","99","VENEGAS","SILLAS","JESUS DE NAZARET","C ALDAMA","35","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("452","1","61","RAMOS","PARTIDA","LORENZO ANTONIO","PROL ABASOLO","3","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("453","1","71","ESPINOBARRO","RUIZ","AGUILAR","C FERROCARRIL","78","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("454","1","61","TOLEDO","MALDONADO","RODOLFO","C MAZATLANCITO","26","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("455","1","38","SALAS","DURAN","MARIA LETICIA","C LIMITE","11","","LOC ACAPONETA","1","1");
INSERT INTO jugadores VALUES("456","1","29","SAENZ","SANCHEZ","MIGUEL","C JUAN ESCUTIA","13","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("457","1","71","BLANCO","ALVALLE","LIONSO ISMAEL","C LIMITE","174","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("458","1","2","BAHENA","RODRIGUEZ","MAYRA PATRICIA","C ALDAMA","41","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("459","1","2","VELAZQUEZ","XX","GREGORIO","C ALDAMA","40 B","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("460","1","75","RANGEL","ALVAREZ","CATALINA","C MAZATLANCITO","30","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("461","1","99","GUARDADO","RODRIGUEZ","GABRIELA","PROL ABASOLO","2 A","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("462","1","19","GOMEZ","FRAYLE","NOE ELOC","C ABASOLO","16","","BARR EL ESTADIO","1","1");
INSERT INTO jugadores VALUES("463","1","19","CASTAEDA","SANCHEZ","CORAL VANESA","C ABASOLO","16","","BARR EL ESTADIO","1","1");
INSERT INTO jugadores VALUES("464","1","2","ONTIVEROS","GARZON","HECTOR JAVIER","C ALDAMA","39 A","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("465","1","60","GARZON","SANCHEZ","JOSE PAZ","C LIMITE","37","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("466","1","3","PEREZ","GUARDADO","YADIRA","C ALDAMA","46 B","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("467","1","60","BERMUDEZ","OCAMPO","ALEJANDRO SALVADOR","C ALDAMA","40","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("468","1","29","GARZON","SERRANO","NEREYDA","C JUAN ESCUTIA","17","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("469","1","29","GUZMAN","FRIAS","VICTOR MANUEL","C JUAN ESCUTIA","17","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("470","1","75","GUARDADO","RODRIGUEZ","ONEIDA","PROL GUADALAJARA","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("471","1","99","RODRIGUEZ","PARTIDA","VALENTIN","C MAZATLANCITO","12","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("472","1","71","VIERA","MORA","VICTOR MANUEL","C ALDAMA","78","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("473","1","99","RODRIGUEZ","BURGARA","MARTHA ELENA","C ALDAMA","21","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("474","1","4","RAMIREZ","SALAZAR","MARIA GUADALUPE","C MAZATLANCITO","2","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("475","1","20","DE LA CRUZ","ALVALLE","MASSIEL ADALBERTO","C LA PAZ","7","","BARRIO EL ESTADIO","1","1");
INSERT INTO jugadores VALUES("476","1","99","TIRADO","AGUILA","JOB ESAU","C ALDAMA","33","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("477","1","99","TIRADO","AGUILA","EUNICE ELIZABETH","C ALDAMA","33","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("478","1","61","RAMIREZ","AVENA","JESUS","PROL ABASOLO","9","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("479","1","3","PEREZ","GUARDADO","NEREIDA","C ALDAMA","46 B","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("480","1","99","MARTINEZ","RODRIGUEZ","ROCIO KARINA","PROL ABASOLO","S/N","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("481","1","2","MAYORQUIN","ORTIZ","ALONDRA EVANGELINA","PROL MATAMOROS","5","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("482","1","71","TOLEDO","LOPEZ","ARELY","C ALDAMA","78","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("483","1","19","AGUILAR","MORENO","ERNESTO FELIPE","C ABASOLO","16","","COL EL ESTADIO","1","1");
INSERT INTO jugadores VALUES("484","1","28","LOPEZ","MEDINA","ROCIO DEL CARMEN","C JUAN ESCUTIA","19","","COL EL ESTADIO","1","1");
INSERT INTO jugadores VALUES("485","1","4","LUNA","SEVILLA","AURELIO","C RAYON","2","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("486","1","61","RAMIREZ","SALAZAR","ANDELISA","PROL GUADALAJARA","2","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("487","1","99","PARTIDA","MAYORQUIN","MARTHA ALICIA","C ALDAMA","25","","COL MAZATLANCITO","1","1");
INSERT INTO jugadores VALUES("488","1","29","ROMERO","SANCHEZ","MARIA JUDITH","C JUAN ESCUTIA","11","","COL EL ESTADIO","1","1");
INSERT INTO jugadores VALUES("489","1","19","TIRADO","LOPEZ","JOSE MIGUEL","C ALDAMA","13","","BARRIO EL ESTADIO","1","1");



DROP TABLE usuario;

CREATE TABLE `usuario` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(50) COLLATE utf8_unicode_ci NOT NULL,
  `password` varchar(60) COLLATE utf8_unicode_ci NOT NULL,
  `rol` varchar(20) COLLATE utf8_unicode_ci DEFAULT NULL,
  `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

INSERT INTO usuario VALUES("1","admin","21232f297a57a5a743894a0e4a801fc3","CAPTURISTA","2016-12-27 08:34:20");
INSERT INTO usuario VALUES("2","pepe","926e27eecdbc7a18858b3798ba99bddd","CAPTURISTA","2016-12-27 09:36:36");
INSERT INTO usuario VALUES("3","pepe","926e27eecdbc7a18858b3798ba99bddd","CAPTURISTA","2016-12-27 09:37:33");



